# Generated by Django 5.0.6 on 2024-05-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(default='default', primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('address', models.CharField(default='default', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('email', models.EmailField(default='default', max_length=254, unique=True)),
                ('phone', models.CharField(default='default', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
